ypl_wechat:
    resource: "@YPLWechatBundle/Resources/config/routing/wechat.xml"
    prefix:   /
    
ypl_wechat_admin:
    resource: "@YPLWechatBundle/Resources/config/routing/admin.xml"
    prefix:   /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
