parameters:
    app_wechat_client_class: Buzz\Client\Curl
    app_wechat_class: YPL\WechatSDK\Wechat
    app_wechat_message_manager_class: YPL\WechatSDK\Model\MessageManager


services:

    app_wechat_client:
        class: %app_wechat_client_class%

    app_wechat_message_manager:
        class: %app_wechat_message_manager_class%


    app_wechat:
        class: %app_wechat_class%
        arguments: [ @app_wechat_client, {appid: %wechat_appid%, appsecret: %wechat_appsecret%, token: %wechat_token% }]
        calls:
            - [setStorage, ["@snc_redis.default"]]



    app.admin.block.wechat:
        class: AppBundle\Block\WechatBlockService
        tags:
            - { name: sonata.block }
        arguments:
            - app.admin.block.wechat
            - @templating